# Generated by Django 2.2.6 on 2019-10-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=200)),
                ('featured', models.BooleanField()),
                ('base', models.CharField(choices=[('Vanilla', 'Vanilla'), ('Chocolate', 'Chocolate')], max_length=20)),
                ('available', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('seasonal', 'Seasonal')], max_length=20)),
                ('date_churned', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
